logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.cloud.gateway: TRACE
#    org.springframework.boot.autoconfigure: DEBUG

server:
  port: 8080

spring:
  autoconfigure:
    # TODO: remove when fixed https://github.com/spring-projects/spring-security/issues/6314
    exclude: org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration
  cloud:
    gateway:
      routes:
        # webflux resource routes
        - id: webflux resource actuator open
          uri: http://localhost:9000
          predicates:
            - Path=/webflux/manage/health
          filters:
            - StripPrefix=1
        - id: webflux resource actuator protected
          uri: http://localhost:9000
          predicates:
            - Path=/webflux/manage/**
          filters:
            - StripPrefix=1
            - TokenRelay
        - id: webflux resource
          uri: http://localhost:9000
          predicates:
            - Path=/webflux/resource
          filters:
            - StripPrefix=1
            - TokenRelay
        # web resource routes
        - id: web resource actuator open
          uri: http://localhost:9001
          predicates:
            - Path=/web/manage/health
          filters:
            - StripPrefix=1
        - id: web resource actuator protected
          uri: http://localhost:9001
          predicates:
            - Path=/web/manage/**
          filters:
            - StripPrefix=1
            - TokenRelay
        - id: web resource
          uri: http://localhost:9001
          predicates:
            - Path=/web/resource
          filters:
            - StripPrefix=1
            - TokenRelay
  security:
    oauth2:
      client:
        registration:
          login-client:
            provider: uaa
            client-id: login-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email,resource.read
        provider:
          uaa:
            authorization-uri: http://localhost:8090/uaa/oauth/authorize
            token-uri: http://localhost:8090/uaa/oauth/token
            user-info-uri: http://localhost:8090/uaa/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://localhost:8090/uaa/token_keys
  thymeleaf:
    cache: false